version: "3.8"
services:
  db:
    image: "postgres:13"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=rambo
      - POSTGRES_DB=booking
