### Get all class types
GET http://localhost:8080/api/classtypes

### Add class type
POST http://localhost:8080/api/classtypes
Content-Type: application/json

{
  "code": "KOODI_6",
  "name": "Koodi 6"
}


### Adding class type with invalid return error
POST http://localhost:8080/api/classtypes
Content-Type: application/json

{
  "code": "KOODI_6! 123456789012345678901234567890X",
  "name": "Koodi 6"
}


### Adding class type without name returns error
POST http://localhost:8080/api/classtypes
Content-Type: application/json

{
  "code": "KOODI6",
  "name": " "
}

### Adding class type with too long code returns error
POST http://localhost:8080/api/classtypes
Content-Type: application/json

{
  "code": "123456789012345678901234567890X",
  "name": "Valid name"
}

### Adding class type with blank code return error
POST http://localhost:8080/api/classtypes
Content-Type: application/json

{
  "code": " ",
  "name": "Valid name"
}

### Get class type by code
GET http://localhost:8080/api/classtypes/KOODI_6

### Get class type with invalid code format fails
GET http://localhost:8080/api/classtypes/KOODI_6!

### Get class type with too long code returns error
GET http://localhost:8080/api/classtypes/123456789012345678901234567890KOODI6

### Delete class type
DELETE http://localhost:8080/api/classtypes/KOODI6

### Delete class type with invalid code format fails
DELETE http://localhost:8080/api/classtypes/KOODI_6!

### Delete class type with too long code returns error
DELETE http://localhost:8080/api/classtypes/123456789012345678901234567890KOODI6


