### Get class type
GET http://localhost:8080/api/classes/types

### Add class type
POST http://localhost:8080/api/classes/types
Content-Type: application/json

{
  "code": "KOODI6",
  "name": "Koodi 6"
}

### Add invalid class type
POST http://localhost:8080/api/classes/types
Content-Type: application/json

{
  "code": "KOODI6",
  "name": ""
}

### Get class type
GET http://localhost:8080/api/classes/types/KOODI6

### Delete class type
DELETE http://localhost:8080/api/classes/types/KOODI6

### Get class definitions
GET http://localhost:8080/api/classes/definitions

